name: IridiumBroadcast
version: '${project.version}'
main: me.xflyiwnl.iridiumbroadcast.Main
api-version: 1.16
authors: [ Iridium ]
description: Плагин на объявления с модерацией
website: vk.com/iridiumstudio

commands:
  iridiumbroadcast:
    aliases:
      - ibc
