
#    ██████╗░██████╗░░█████╗░░█████╗░██████╗░░█████╗░░█████╗░░██████╗████████╗
#    ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝╚══██╔══╝
#    ██████╦╝██████╔╝██║░░██║███████║██║░░██║██║░░╚═╝███████║╚█████╗░░░░██║░░░
#    ██╔══██╗██╔══██╗██║░░██║██╔══██║██║░░██║██║░░██╗██╔══██║░╚═══██╗░░░██║░░░
#    ██████╦╝██║░░██║╚█████╔╝██║░░██║██████╔╝╚█████╔╝██║░░██║██████╔╝░░░██║░░░
#    ╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░

settings:

  #   Формат объявления:
  #   {prefix} = префикс
  #   {broadcast} = объявление
  #   {player} = автор
  #   {admin} = администратор

  broadcast-format:
    - "{prefix} &f{broadcast} &2(Автор: {player})"
    - " &2› &fПроверил администратор - &2{admin}"

  #   Кулдаун на команду /ibc broadcast

  broadcast-cooldown: 30

  #   Стоимость объявления

  broadcast-cost: 100